quarter = x => Math.floor(x/4);

lo = x => x & 0xff;
hi = x => (x & 0xffff) >> 8;



function table(name, len, fn) {
    if (len % 256 != 0) {
        throw new Error("bad len");
    }
    
    let elems = [...Array(len)].map((_,i) => fn(i));

    return `const uint8_t ${name}[${len}] = {
    ${elems}
};
#pragma align(${name}, 256)`
}


`// generated by imul_const.js
#include "imul.h"


#include <stdint.h>


#pragma code(code63)
#pragma data(data63)

${table('sqrlo', 512, i => lo(quarter(i**2)))}
${table('sqrhi', 512, i => hi(quarter(i**2)))}


${table('negsqrlo', 512, i => lo(quarter((255-i)**2)))}
${table('negsqrhi', 512, i => hi(quarter((255-i)**2)))}
`