from .util import lsb, msb


def table(name, length, fn):
    if length % 256 != 0:
        raise ValueError("bad len")
    
    elems = [fn(i) for i in range(length)]
    elems_str = ','.join(str(e) for e in elems)
    
    return f"""const uint8_t {name}[{length}] = {{
    {elems_str}
}};
#pragma align({name}, 256)"""


def gen_imul_const():
    return f"""// generated by codegen.py
#include "imul.h"


#include <stdint.h>


#pragma code(code63)
#pragma data(data63)
#pragma bss(bss)

{table('sqrlo', 512, lambda i: lsb(i**2 // 4))}
{table('sqrhi', 512, lambda i: msb(i**2 // 4))}


{table('negsqrlo', 512, lambda i: lsb((255-i)**2 // 4))}
{table('negsqrhi', 512, lambda i: msb((255-i)**2 // 4))}
"""